name: Exemple de pipeline CI/CD avec secret GCP

on:
  push:
    branches:
      - main  # Remplacez par la branche de votre choix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Utilisation du secret GCP
      env:
        GCP_AUTH_KEY: ${{ secrets.GCP_AUTH_KEY }}
      run: |
        touch gcp-key.json
        echo "$GCP_AUTH_KEY" > gcp-key.json
        cat gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json

        # Configurez ici les commandes pour exécuter vos migrations ou d'autres tâches GCP
        # Par exemple :
        # gcloud compute instances list

    - name: Exécution des migrations de base de données avec dbmate
      run: |
        # Remplacez les valeurs suivantes par les vôtres
        DB_HOST="34.155.64.154"
        DB_PORT="5432"
        DB_USER="testMedium"
        DB_PASS="secretMedium"
        DB_NAME="test-db"
        curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
        chmod +x /usr/local/bin/dbmate
        # Exécutez la migration avec dbmate
        dbmate -u "postgres://testMedium:secretMedium@34.155.64.154:5432/testcloudSqlInstance=slacklinemailling:europe-west9:test-db" migrate
  
    - name: Nettoyage
      run: |
        rm -f gcp-key.json

  # Ajoutez d'autres étapes selon vos besoins
